HW-5 solution
mate-academy/layout_style-it-up pull request #129
Opened 2019-07-23 10:24 UTC by KosBelozyorov

2019-07-23 14:49 UTC, YuriiHoliuk requested changes

2019-07-23 14:49 UTC, YuriiHoliuk commented on readme.md
> +- [UPDATE DEMO LINK](https://KosBelozyorov.github.io/layout_style-it-up/)
The height of each of the blocks (including both header and footer)

> hover on header and footer do not works

2019-07-23 14:49 UTC, YuriiHoliuk commented on src/style.css
> +  width: 300px;
write these styles in previous declaration

2019-07-23 14:49 UTC, YuriiHoliuk commented on src/style.css
> +.surprising:hover {
group declarations with hover same as above

2019-07-23 16:42 UTC, KosBelozyorov commented
fix style.css

2019-07-24 13:06 UTC, YuriiHoliuk approved these changes

2025-09-21 21:11 UTC, closed without merging