style-it-up complete
mate-academy/layout_style-it-up pull request #430
Opened 2020-08-26 11:31 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/layout_style-it-up/) <br>
[TEST REPORT LINK](https://andlap24.github.io/layout_style-it-up/report/html_report/)

2020-08-26 15:10 UTC, solaryasha requested changes

2020-08-26 15:10 UTC, solaryasha commented on src/style.css
> +  height: 100px;
спробуй не повторюватися і запиши такі самі стилі через кому
Наприклад, `.interesting, .surprising, #footer ` { cхожі стилі }

2020-08-26 15:52 UTC, andlap24 commented on src/style.css
> +  height: 100px;
пофіксив:) буду памятати за це

2020-08-27 06:23 UTC, solaryasha approved these changes
Well done !

2020-10-02 13:34 UTC, closed without merging